<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://cmp1144.pucgoias.br" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://cmp1144.pucgoias.br" xmlns:intf="http://cmp1144.pucgoias.br" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="PrimeiroServico">

   </wsdl:portType>

   <wsdl:binding name="PrimeiroServicoSoapBinding" type="impl:PrimeiroServico">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="PrimeiroServicoService">

      <wsdl:port binding="impl:PrimeiroServicoSoapBinding" name="PrimeiroServico">

         <wsdlsoap:address location="http://localhost:8080/ex005/services/PrimeiroServico"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
